#!perl -w
use strict;

use YAML;

my $all_input = join "", <>;
my $h = Load($all_input);

print '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
  <head>
    <title>Manager documentation</title>
    <style type="text/css">
      body {
        font-size: 80%;
        font-family: "Lucida Grande", Verdana, Arial, Sans-Serif;
      }
      h2 {
        border-bottom: solid 1px black;
      }
      .description {
        background: #fcc;
        border: solid 1px #800;
        padding: 1em;
      }
      .method {
        background: #ccc;
        border: solid 1px #444;
        padding: 0.5em 1em 0.5em 1em;
        margin: 1em;
      }
    </style>
  </head>
<body>';

# Sort alphabetically on the first namespace
sub by_namespace {
    $h->{$a}{Namespaces}[0] cmp $h->{$b}{Namespaces}[0];
}
my @managers = sort by_namespace keys %{$h};

print "<ul>\n";
for my $manager (@managers) {
    my $namespaces = join ', ', @{$h->{$manager}{Namespaces}};
    my $first_ns = $h->{$manager}{Namespaces}[0];
    print "<li><a href='#$first_ns'>$namespaces</a></li>\n";
}
print "</ul>\n";

for my $manager (@managers) {
    my $namespaces = join ', ', @{$h->{$manager}{Namespaces}};
    my $first_ns = $h->{$manager}{Namespaces}[0];
    print "<h2 id='$first_ns'>$namespaces</h2>\n";
    print "<p class='description'>", $h->{$manager}{Description}, "</p>\n";

    for my $m (@{$h->{$manager}{Methods}}) {
        print "<div class='method'>\n";
        my $k = (keys(%$m))[0];
        print "<h3>$k</h3>\n<dl>\n";
        for my $kk (qw<summary params>) {
            my @a = @{$m->{$k}};
            for my $plx (@a) {
                my $vv = $plx->{$kk} || '';
                # Used HTML::EscapeEvil, but the module truncated the text for
                # some reason. Doing it manually instead.
                $vv =~ s/&/\&amp;/;
                $vv =~ s/</\&lt;/;
                $vv =~ s/>/\&gt;/;
                $vv =~ s/'/\&quot;/;
                $vv =~ s/"/\&#34;/;
                # Java newlines replaced by HTML newlines
                $vv =~ s/\\n/<br>/;
                if ($vv) {
                    print "<dt>$kk</dt><dd>$vv</dd>\n"
                }
            }
        }
        print "</dl>\n</div>\n"
    }
}
print "</body>\n</html>\n";
