#!perl -w
use strict;

use YAML;
use HTML::EscapeEvil;

my $a = join "", <>;
my $h = Load($a);

my $escaper = HTML::EscapeEvil->new();

print '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">' . "\n<html><head><title>Manager documentation</title><style type='text/css'>body { font-size: 80%; font-family: 'Lucida Grande', Verdana, Arial, Sans-Serif; } h2 { border-bottom: solid 1px black; }\n\n.description { background: #fcc; border: solid 1px #800; padding: 1em; } .method { background: #ccc; border: solid 1px #444; padding: 0.5em 1em 0.5em 1em; margin: 1em; }</style></head>\n<body>\n";

my @managers = sort keys %{$h};

print "<ul>\n";
for my $manager (@managers) {
    print "<li><a href='#$manager'>$manager</a></li>\n";
}
print "</ul>\n";

for my $manager (@managers) {
    print "<h2 id='$manager'>$manager</h2>\n";
    print "<p class='description'>", $h->{$manager}{Description}, "</p>\n";

    for my $m (@{$h->{$manager}{Methods}}) {
        print "<div class='method'>\n";
        my $k = (keys(%$m))[0];
        print "<h3>$k</h3>\n<dl>\n";
        for my $kk (qw<summary params>) {
            my @a = @{$m->{$k}};
            for my $plx (@a) {
                my $vv = $escaper->parse($plx->{$kk} || '')->filtered_html();
                $escaper->clear();
                if ($vv) {
                    print "<dt>$kk</dt><dd>$vv</dd>\n"
                }
            }
        }
        print "</dl>\n</div>\n"
    }
}
print "</body>\n</html>\n";
