#!/bin/bash

# This file is meant to be run like this:
#
# ./run-the-whole-thing > html/index.html

if (which tidy > /dev/null); then
    # we have tidy -- do a null command to make bash happy
    true
else
    echo 'Grab tidy at <http://tidy.sourceforge.net/>' >&2;
    exit;
fi

. find-published-classes |
    xargs perl parse-file-for-annotations |
    perl render-as-html |
    tidy -i 2> /dev/null
