#!/bin/bash

# This file is meant to be run like this:
#
# ./run-the-whole-thing > html/index.html

if (which tidy > /dev/null); then
    # we have tidy -- do a null command to make bash happy
    true
else
    echo 'Grab tidy at <http://tidy.sourceforge.net/>' >&2;
    exit;
fi

perl find-published-classes |
    xargs perl parse-file-for-annotations > stage1

if [ $? != 0 ]; then
    exit 1;
fi

perl render-as-html stage1 |
    tidy -i 2> tidy_errors

if [ $? != 0 ]; then
    cat tidy_errors >&2;
    exit 1;
fi

rm -f stage1 tidy_errors
